
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyrssfvewtdqzzoqohyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5cnNzZnZld3RkcXp6b3FvaHlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxODA5MjIsImV4cCI6MjA1Nzc1NjkyMn0.zNQjBVcgXxsdHgI_cJ2taP61WkFUUWJvUs4DxnrTvOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true
  }
});
